
# This file is automatically generated, you probably don't want to edit this

qualitativeOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "qualitativeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            splitBy = NULL,
            pcCol = TRUE,
            pcRow = FALSE,
            pcTotal = FALSE, ...) {

            super$initialize(
                package="jmv",
                name="qualitative",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                permitted=list(
                    "factor"))
            private$..splitBy <- jmvcore::OptionVariable$new(
                "splitBy",
                splitBy,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor",
                    "numeric",
                    "id"),
                default=NULL)
            private$..pcCol <- jmvcore::OptionBool$new(
                "pcCol",
                pcCol,
                default=TRUE)
            private$..pcRow <- jmvcore::OptionBool$new(
                "pcRow",
                pcRow,
                default=FALSE)
            private$..pcTotal <- jmvcore::OptionBool$new(
                "pcTotal",
                pcTotal,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..splitBy)
            self$.addOption(private$..pcCol)
            self$.addOption(private$..pcRow)
            self$.addOption(private$..pcTotal)
        }),
    active = list(
        vars = function() private$..vars$value,
        splitBy = function() private$..splitBy$value,
        pcCol = function() private$..pcCol$value,
        pcRow = function() private$..pcRow$value,
        pcTotal = function() private$..pcTotal$value),
    private = list(
        ..vars = NA,
        ..splitBy = NA,
        ..pcCol = NA,
        ..pcRow = NA,
        ..pcTotal = NA)
)

qualitativeResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "qualitativeResults",
    inherit = jmvcore::Group,
    active = list(
        freqs = function() private$.items[["freqs"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Zmienne jakosciowe")
            self$add(jmvcore::Array$new(
                options=options,
                name="freqs",
                title="Tabele czestosci",
                items="(vars)",
                template=jmvcore::Table$new(
                    options=options,
                    title="$key",
                    clearWith=list(
                        "splitBy",
                        "pcCol",
                        "pcRow",
                        "pcTotal"),
                    columns=list())))}))

qualitativeBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "qualitativeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmv",
                name = "qualitative",
                version = c(1,0,0),
                options = options,
                results = qualitativeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Zmienne jakosciowe
#'
#' 
#' @param data .
#' @param vars zmienne jakosciowe (factor)
#' @param splitBy zmienna grupujaca (factor)
#' @param pcCol procenty w kolumnie (po grupach)
#' @param pcRow procenty w wierszu
#' @param pcTotal procenty z calkowitej liczby obserwacji
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$freqs} \tab \tab \tab \tab \tab tabele czestosci dla zmiennych jakosciowych \cr
#' }
#'
#' @export
qualitative <- function(
    data,
    vars,
    splitBy = NULL,
    pcCol = TRUE,
    pcRow = FALSE,
    pcTotal = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("qualitative requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(splitBy)) splitBy <- jmvcore::resolveQuo(jmvcore::enquo(splitBy))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(splitBy), splitBy, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- qualitativeOptions$new(
        vars = vars,
        splitBy = splitBy,
        pcCol = pcCol,
        pcRow = pcRow,
        pcTotal = pcTotal)

    analysis <- qualitativeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

