
# This file is automatically generated, you probably don't want to edit this

simpleCorrOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "simpleCorrOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            var1 = NULL,
            var2 = NULL,
            method = "pearson",
            pValue = TRUE,
            showPlot = TRUE, ...) {

            super$initialize(
                package="jmv",
                name="simpleCorr",
                requiresData=TRUE,
                ...)

            private$..var1 <- jmvcore::OptionVariable$new(
                "var1",
                var1,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..var2 <- jmvcore::OptionVariable$new(
                "var2",
                var2,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "pearson",
                    "spearman"),
                default="pearson")
            private$..pValue <- jmvcore::OptionBool$new(
                "pValue",
                pValue,
                default=TRUE)
            private$..showPlot <- jmvcore::OptionBool$new(
                "showPlot",
                showPlot,
                default=TRUE)

            self$.addOption(private$..var1)
            self$.addOption(private$..var2)
            self$.addOption(private$..method)
            self$.addOption(private$..pValue)
            self$.addOption(private$..showPlot)
        }),
    active = list(
        var1 = function() private$..var1$value,
        var2 = function() private$..var2$value,
        method = function() private$..method$value,
        pValue = function() private$..pValue$value,
        showPlot = function() private$..showPlot$value),
    private = list(
        ..var1 = NA,
        ..var2 = NA,
        ..method = NA,
        ..pValue = NA,
        ..showPlot = NA)
)

simpleCorrResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "simpleCorrResults",
    inherit = jmvcore::Group,
    active = list(
        table = function() private$.items[["table"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Prosta korelacja")
            self$add(jmvcore::Table$new(
                options=options,
                name="table",
                title="Korelacja",
                rows=1,
                clearWith=list(
                    "var1",
                    "var2",
                    "method"),
                columns=list(
                    list(
                        `name`="var1", 
                        `title`="Zmienna 1", 
                        `type`="text"),
                    list(
                        `name`="var2", 
                        `title`="Zmienna 2", 
                        `type`="text"),
                    list(
                        `name`="r", 
                        `title`="r", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(pValue)"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Wykres rozrzutu",
                visible="(showPlot)",
                width=500,
                height=400,
                renderFun=".scatterPlot",
                clearWith=list(
                    "var1",
                    "var2",
                    "method")))}))

simpleCorrBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "simpleCorrBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmv",
                name = "simpleCorr",
                version = c(1,0,0),
                options = options,
                results = simpleCorrResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Prosta korelacja
#'
#' 
#' @param data .
#' @param var1 .
#' @param var2 .
#' @param method .
#' @param pValue .
#' @param showPlot .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$table$asDF}
#'
#' \code{as.data.frame(results$table)}
#'
#' @export
simpleCorr <- function(
    data,
    var1,
    var2,
    method = "pearson",
    pValue = TRUE,
    showPlot = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("simpleCorr requires jmvcore to be installed (restart may be required)")

    if ( ! missing(var1)) var1 <- jmvcore::resolveQuo(jmvcore::enquo(var1))
    if ( ! missing(var2)) var2 <- jmvcore::resolveQuo(jmvcore::enquo(var2))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(var1), var1, NULL),
            `if`( ! missing(var2), var2, NULL))


    options <- simpleCorrOptions$new(
        var1 = var1,
        var2 = var2,
        method = method,
        pValue = pValue,
        showPlot = showPlot)

    analysis <- simpleCorrClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

